/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package covid19Tracker;

import covid19Tracker.infrastructure.web.Webserver;

public class Main {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) throws Exception {
        System.out.println(new Main().getGreeting());
        new Webserver().startJetty();
    }
}
