/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package covid19Tracker;

import covid19Tracker.application.AccountService;
import covid19Tracker.infrastructure.UserGenerator;
import covid19Tracker.infrastructure.database.ConnectToDatabase;
import covid19Tracker.infrastructure.database.DeleteInDatabase;
import covid19Tracker.infrastructure.database.InitDatabase;
import covid19Tracker.infrastructure.database.InsertInDatabase;
import covid19Tracker.infrastructure.web.CorsHandler;
import covid19Tracker.infrastructure.web.Webserver;

import java.sql.Connection;

public class Main {

    public static void main(String[] args) throws Exception {
        String database_url = System.getenv("DATABASE_URL");
        String host = "";
        String user = "";
        String password = "";
        String database = "";

        if(database_url != null && !database_url.isEmpty()){
            host = database_url.substring(91, 132);
            user = database_url.substring(11, 25);
            password = database_url.substring(26, 90);
            database = database_url.substring(138, 152);
        } else {
            host = System.getenv("DBHOST");
            user = System.getenv("DBUSER");
            password = System.getenv("DBPWD");
            database = System.getenv("DB");
        }

        if(host == null || host.isEmpty() || user == null || user.isEmpty() || password == null || password.isEmpty() || database == null || database.isEmpty()){
            System.err.println("Missing environment variables");
            System.exit(1);
        }
        System.out.printf("Starting app with host: %s, user: %s, database: %s, password %s\n",host,user,database,password);

        InitDatabase initDatabase = new InitDatabase(host, user, password, database);
        initDatabase.initiateDatabase();

        ConnectToDatabase connectToDatabase = new ConnectToDatabase(host, user, password, database);
        Connection connection = connectToDatabase.connect();

        DeleteInDatabase deleteInDatabase = new DeleteInDatabase(connection);
        deleteInDatabase.validateCode("1234#abcde");
        InsertInDatabase insertInDatabase = new InsertInDatabase(connection);

        UserGenerator userGenerator = new UserGenerator();
        AccountService accountService = new AccountService(userGenerator, insertInDatabase);

        CorsHandler corsHandler = new CorsHandler();
        new Webserver(accountService, corsHandler, deleteInDatabase).startJetty();
    }
}